services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  fake-sources:
    build: ./fake-sources
    environment:
      - BACKEND_URL=http://backend:8080
      - INTERVAL_SECONDS=5
    depends_on:
      - backend

  xmpp:
    image: ghcr.io/processone/ejabberd:25.10
    ports:
      - "5222:5222"   # XMPP client port
      - "5280:5280"   # Web admin UI (localhost:5280/admin)
    environment:
      - REGISTER_ADMIN_PASSWORD=changeme
      - CTL_ON_CREATE=register backend localhost changeme ;
                        register unit-07 localhost changeme ;
                        register unit-12 localhost changeme ;
                        register gate-A localhost changeme ;
                        register gate-B localhost changeme ;
                        register beacon-03 localhost changeme
