spring.application.name=backend
spring.devtools.livereload.enabled=true

xmpp.server.host=xmpp
xmpp.server.port=5222
xmpp.server.domain=localhost
xmpp.backend.username=backend
xmpp.backend.password=changeme

spring.datasource.url=jdbc:postgresql://db:5432/assetmonitor
spring.datasource.username=assetmonitor
spring.datasource.password=changeme
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false