spring.application.name=backend
spring.devtools.livereload.enabled=true

xmpp.server.host=xmpp
xmpp.server.port=5222
xmpp.server.domain=localhost
xmpp.backend.username=backend
xmpp.backend.password=changeme